language: go

go:
  - "1.13"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3 libsqlite3-dev

script:
  - make && make sec && make coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
