language: go

go:
  - 1.9.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3 libsqlite3-dev

script:
  - make && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
