language: go

go:
  - 1.9.x
  - 1.8.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3 libsqlite3-dev
  - go get github.com/mattn/goveralls

script:
  - make
  - $GOPATH/bin/goveralls -service=travis-ci
