#!/usr/bin/env bash

# use to set up a local vm to test the server

set -euo pipefail
# ref: http://redsymbol.net/articles/unofficial-bash-strict-mode/

API_ROOT_PATH="cabby_test_root"
API_ROOT_TITLE="a cabby api root"
API_ROOT_MAX_CONTENT_LENGTH=8388608
API_ROOT_VERSION="taxii-2.0"

COLLECTION_ID="352abc04-a474-4e22-9f4d-944ca508e68c"
COLLECTION_TITLE="a collection title"

DISCOVERY_CONTACT="github.com/pladdy"
DISCOVERY_DEFAULT="https://localhost/taxii/"
DISCOVERY_DESCRIPTION="test cabby server"
DISCOVERY_TITLE="test cabby server"

TAXII_USER="test@cabby.com"
TAXII_PASSWORD="test-password"

cabby-certs

cabby-cli create user -u "$TAXII_USER" -p "$TAXII_PASSWORD" -a
cabby-cli create discovery -d "$DISCOVERY_DESCRIPTION" -t "$DISCOVERY_TITLE" -u "$DISCOVERY_DEFAULT" -c "$DISCOVERY_CONTACT"
cabby-cli create apiRoot -a "$API_ROOT_PATH" -t "$API_ROOT_TITLE" -m "$API_ROOT_MAX_CONTENT_LENGTH" -v "$API_ROOT_VERSION"
cabby-cli create collection -a "$API_ROOT_PATH" -t "$COLLECTION_TITLE" -i "$COLLECTION_ID"
cabby-cli create userCollection -u "$TAXII_USER" -i "$COLLECTION_ID" -r -w
