#!/usr/bin/env bash

# helper script used to set up a local sqlite db for cabby

set -euo pipefail
# ref: http://redsymbol.net/articles/unofficial-bash-strict-mode/

API_ROOT_PATH="cabby_test_root"
API_ROOT_TITLE="a cabby api root"
API_ROOT_MAX_CONTENT_LENGTH=8388608
API_ROOT_VERSION="taxii-2.0"

CABBY_SCHEMA="sqlite/schema.sql"

COLLECTION_ID="352abc04-a474-4e22-9f4d-944ca508e68c"
COLLECTION_TITLE="a collection title"

CONFIG_PATH="config/cabby.json"

DISCOVERY_CONTACT="github.com/pladdy"
DISCOVERY_DEFAULT="https://localhost/taxii/"
DISCOVERY_DESCRIPTION="test cabby server"
DISCOVERY_TITLE="test cabby server"

TAXII_USER="test@cabby.com"
TAXII_PASSWORD="test-password"

# set up db
DB_PATH="$(jq .data_store.path $CONFIG_PATH | sed 's/\"//g')"
DB_DIR="$(dirname $DB_PATH)"
mkdir -p "$DB_DIR"
sqlite3 "$DB_PATH" ".read $CABBY_SCHEMA"

cmd/cabby-cli/cabby-cli --config "$CONFIG_PATH" create user -u "$TAXII_USER" -p "$TAXII_PASSWORD" -a
cmd/cabby-cli/cabby-cli --config "$CONFIG_PATH" create discovery -d "$DISCOVERY_DESCRIPTION" -t "$DISCOVERY_TITLE" -u "$DISCOVERY_DEFAULT" -c "$DISCOVERY_CONTACT"
cmd/cabby-cli/cabby-cli --config "$CONFIG_PATH" create apiRoot -a "$API_ROOT_PATH" -t "$API_ROOT_TITLE" -m "$API_ROOT_MAX_CONTENT_LENGTH" -v "$API_ROOT_VERSION"
cmd/cabby-cli/cabby-cli --config "$CONFIG_PATH" create collection -a "$API_ROOT_PATH" -t "$COLLECTION_TITLE" -i "$COLLECTION_ID"
cmd/cabby-cli/cabby-cli --config "$CONFIG_PATH" create userCollection -u "$TAXII_USER" -i "$COLLECTION_ID" -r -w
