#!/usr/bin/env bash

## set up script to test out a running server

make sqlite

# set up user
TEST_USER=test@cabby.com

pass=`printf test | sha256sum | cut -d '-' -f 1 | xargs`
sqlite3 db/cabby.db "insert into taxii_user (email) values('${TEST_USER}')"
sqlite3 db/cabby.db "insert into taxii_user_pass (email, pass) values('${TEST_USER}', '${pass}')"

# set up discovery
sqlite3 db/cabby.db "
insert into taxii_discovery (title, description, contact, default_url) values(
  'a local taxii 2 server',
  'this is a test taxii2 server written in golang',
  'github.com/pladdy',
  'https://localhost/taxii/'
)"

# set up api root
API_ROOT=cabby_test_root

sqlite3 db/cabby.db "
insert into taxii_api_root (id, api_root_path, title, description, versions, max_content_length) values (
  'testId',
  '${API_ROOT}',
  'a title',
  'a description',
  'application/vnd.oasis.stix+json; version=2.0',
  8388608 /* 8 MB */
)"

# set up collection
COLLECTION_ID=352abc04-a474-4e22-9f4d-944ca508e68c

sqlite3 db/cabby.db "
insert into taxii_collection (id, api_root_path, title, description, media_types) values (
  '${COLLECTION_ID}',
  '${API_ROOT}',
  'a test collection',
  'a test collection description',
  ''
)"

sqlite3 db/cabby.db "
insert into taxii_user_collection (email, collection_id, can_write, can_read) values (
  '${TEST_USER}',
  '${COLLECTION_ID}',
  1,
  1
)"
